### ISSUE TITLE
Не очень понятно для чего приведение к строке. Можно было бы обойтись без этого действия

### ISSUE THREAD

**Issue by m4tut** [dudeVladimir/rock-paper-scissors#7]
https://github.com/dudeVladimir/rock-paper-scissors/blob/aafad2f5d524baf6097f223298f27bf7c7d912ef/src/App.vue#L66

**Comment by dudeVladimir** [comment]
ts ругается если передавать значение не в формате строки, ибо localStorage
поэтому такое решение :)
